### ISSUE TITLE
Byte > Booking is not working on clicking the icon

### ISSUE THREAD

**Issue by bidyut-majumdar** [manojnegi07/social-external#1011]
![bookmark not workinbg](https://github.com/manojnegi07/social-external/assets/78781245/ae27b7f9-a250-4f09-b31e-8aa367d3da21)

**Comment by manojnegi07** [comment]
@Anupriyabanger  here we are bookmarking the byte which will be visible on bookmark section not on byte. changing the toast text and moving it to review required
