### ISSUE TITLE
Byte listing > When sharing a byte, the like options are appearing inside the container of existing byte container, it should be outside where the main byte is being shared.

### ISSUE THREAD

**Issue by bidyut-majumdar** [manojnegi07/social-external#1032]
![11](https://github.com/manojnegi07/social-external/assets/78781245/1057f99e-0f51-4e4b-8808-9e405cc256dd)

**Comment by manojnegi07** [comment]
@vayuzpriya  you asked me to do this

**Comment by vayuzpriya** [comment]
Not like this
please connect with me for this
