### ISSUE TITLE
Byte > Bookmark saving gives wrong confirmation message "Byte created", it should be "Bookmark saved".

### ISSUE THREAD

**Issue by bidyut-majumdar** [manojnegi07/social-external#1051]
![Screenshot 2023-09-10 215137](https://github.com/manojnegi07/social-external/assets/78781245/c43f5107-5df7-41e4-a785-a05487be0b98)

**Comment by rgnarok** [comment]
No toast coming up please fix

**Comment by manojnegi07** [comment]
![image](https://github.com/manojnegi07/social-external/assets/92147060/7d60c952-2546-41db-baf5-67a6d39f19b9)
