### ISSUE TITLE
Byte reaction > Upon hovering on a already reacted emoji panel the first like icon is positioned incorrectly

### ISSUE THREAD

**Issue by bidyut-majumdar** [manojnegi07/social-external#1058]
![8](https://github.com/manojnegi07/social-external/assets/78781245/1df064a1-1d56-49b2-8722-9be8f9d36caa)

![9](https://github.com/manojnegi07/social-external/assets/78781245/f6cdc93e-aff4-4197-a369-bb432f5181ed)

**Comment by vayuzpriya** [comment]
Icon Changed. but cant fix the position
