### ISSUE TITLE
Suggestion: Byte listing> Same emojis shown

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#1066]
Same emojis twice doesn't look good, we can use connections profile images
![image](https://github.com/manojnegi07/social-external/assets/109590553/77250f24-cc7c-4b6c-9eea-a23f35762faa)
Expectation: ![image](https://github.com/manojnegi07/social-external/assets/109590553/8f92f5dd-e78e-4e33-b3f0-5601497d575e)

**Comment by vayuzpriya** [comment]
@Anupriyabanger we removed the emojies

**Comment by vayuzpriya** [comment]
We can't show profile image here 
Profile images is not look good
