### ISSUE TITLE
Create byte> Background> blanks should not be visible

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#1091]
![image](https://github.com/manojnegi07/social-external/assets/109590553/10a220e1-305f-4e1d-a478-bd17102a8e02)

**Comment by rgnarok** [comment]
<img width="718" alt="image" src="https://github.com/manojnegi07/social-external/assets/85341053/9d8ec72b-be69-4307-9772-4f4198fd5752">

Visible on more please fix
