### ISSUE TITLE
Byte> upload PDF> Add loader 

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#1092]
![image](https://github.com/manojnegi07/social-external/assets/109590553/b5b258ee-f736-4886-acdc-913730199892)

**Comment by vayuzpriya** [comment]
UI fIx here, 
@manojnegi07 Pls add same loader here like byte

**Comment by Anupriyabanger** [comment]
@manojnegi07 no loader added on uploading doc
