### ISSUE TITLE
Byte> Create byte Add loader

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#1093]
![image](https://github.com/manojnegi07/social-external/assets/109590553/611d29d8-284e-4385-9303-1bfb1c9fd5fe)

**Comment by rgnarok** [comment]
Can we have a proper loader instead of a text-based loader? Any proper animation which ca be used for all

**Comment by vayuzpriya** [comment]
https://user-images.githubusercontent.com/81085431/278303200-dcc97513-bddc-4124-962b-ec1676c3b282.png

**Comment by vayuzpriya** [comment]
![278303200-dcc97513-bddc-4124-962b-ec1676c3b282](https://github.com/manojnegi07/social-external/assets/81085431/44671d12-eeeb-4a37-92a7-26a3d7f440b8)
