### ISSUE TITLE
Byte> Unable to upload videos on Social Bytes via mobile

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#1100]
![image](https://github.com/manojnegi07/social-external/assets/109590553/1e8330cd-be6d-41bb-98d1-3b089288d1e5)

**Comment by manojnegi07** [comment]
Large Videos not allowed for now

**Comment by Anupriyabanger** [comment]
Uploaded 16.48MBfile, worked smoothly
