### ISSUE TITLE
Byte> Crete byte box UI is completely messed up

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#1101]
![image](https://github.com/manojnegi07/social-external/assets/109590553/f508347f-4f0c-4e80-b9ca-f1a582d1ba21)

**Comment by vayuzpriya** [comment]
- [ ] border in editor
- [ ] Text area background color should be dark in dark mode 
- [ ] if image is not uploaded then show error message in place of loader of image
- [ ] button border should be dark

**Comment by vayuzpriya** [comment]
@manojnegi07 Pls check your pointer here 


- [ ] when we upload images and remove Editor background color is
