### ISSUE TITLE
Byte> How to X out of this screen (like / comment / reactions)

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#1107]
![image](https://github.com/manojnegi07/social-external/assets/109590553/ba7dc2b2-4237-4c37-862b-4bd90f7eefc7)

**Comment by vayuzpriya** [comment]
comment screen - 
![image](https://github.com/manojnegi07/social-external/assets/81085431/6948adc1-0284-4f13-af6b-e9400802ea4d)
and 
like screen 
![image](https://github.com/manojnegi07/social-external/assets/81085431/9294e5e7-6f77-4441-9fae-be07d90952d3)
