### ISSUE TITLE
Byte listing > Event > Clicking on "Pending action" to "Attending" doesn't change the state to "Attending", it remains same "Pending action"

### ISSUE THREAD

**Issue by bidyut-majumdar** [manojnegi07/social-external#1126]
![2023-10-12_093106](https://github.com/manojnegi07/social-external/assets/78781245/baaedcc2-7050-4c70-9a46-ec35a15cb42b)

**Comment by Anupriyabanger** [comment]
UI changed, removed 3 dots on byte listing
