### ISSUE TITLE
Insights: Meta needs to be configured for listing

### ISSUE THREAD

**Issue by technicalbirdVayuz** [manojnegi07/social-external#1149]

**Comment by manojnegi07** [comment]
@technicalbirdVayuz  please explain this one. not clear

**Comment by technicalbirdVayuz** [comment]
Please add meta specific for insights on insight.vayuz.com, currently default meta for social going on to this page

https://www.heymeta.com/url/insight.vayuz.com

**Comment by manojnegi07** [comment]
@Anupriyabanger 
please provide following content
Meta Description for insight
Meta title for insight
Meta image for insight
Meta Keyworkds For insight

**Comment by Anupriyabanger** [comment]
Meta Description for insight: Discover cutting-edge insights on technology and innovation with VAYUZ Technologies. Dive deep into emerging trends and actionable analyses to propel your business in the digital era.

Meta title for insight: VAYUZ Technologies Insights: Expert Perspectives on Technology & Innovation

Meta Keywords For insight: VAYUZ Technologies, insights, blog, technology, innovation, trends, analysis, business strategies, digital transformation, thought leadership

Meta image for insight: VAYUZ Logo
