### ISSUE TITLE
Insights: Slider is not uniform

### ISSUE THREAD

**Issue by technicalbirdVayuz** [manojnegi07/social-external#1151]
Its open with 2 images like this
<img width="1440" alt="Screenshot 2023-10-17 at 12 09 45 PM" src="https://github.com/manojnegi07/social-external/assets/18699624/b2c8b3a1-cd86-4770-b182-4f44705143cc">

clicking on right side 2 times makes it like this
 
<img width="1440" alt="Screenshot 2023-10-17 at 12 09 50 PM" src="https://github.com/manojnegi07/social-external/assets/18699624/1faf8e40-dab8-4d91-980d-e6de1a0a9ff2">

**Comment by manojnegi07** [comment]
![image](https://github.com/manojnegi07/social-external/assets/92147060/8310c5a9-cf38-4242-ae6a-ff17e48bed65)
It is coming like this on my device. it may be the issue of screen size

**Comment by vayuzpriya** [comment]
now one slide is visible at one time and slide uniformly 
Pls check and your end and close the issue.
