### ISSUE TITLE
Insights: Can we use icons, its not intuitive that user will click on list as a text and that will open a dropdown

### ISSUE THREAD

**Issue by technicalbirdVayuz** [manojnegi07/social-external#1156]
<img width="1439" alt="Screenshot 2023-10-17 at 12 13 12 PM" src="https://github.com/manojnegi07/social-external/assets/18699624/b5c4fae7-f595-4448-a74b-b690baf02e20">

Please use icons or try to highlight in a better way

**Comment by vayuzpriya** [comment]
https://github.com/manojnegi07/social-external/issues/1155
duplicate
