### ISSUE TITLE
Insights: 3 dots are not aligned

### ISSUE THREAD

**Issue by technicalbirdVayuz** [manojnegi07/social-external#1158]
<img width="1439" alt="Screenshot 2023-10-17 at 12 15 36 PM" src="https://github.com/manojnegi07/social-external/assets/18699624/4ca31996-3281-4a80-8688-c3824f60d4a5">

It should be more on the right side

**Comment by vayuzpriya** [comment]
https://github.com/manojnegi07/social-external/issues/1174
https://github.com/manojnegi07/social-external/issues/1506
