### ISSUE TITLE
Insights: Can we make these categories based on the no of insights each category have, currently its random, travel is second category but only have one insight

### ISSUE THREAD

**Issue by technicalbirdVayuz** [manojnegi07/social-external#1161]
<img width="1439" alt="Screenshot 2023-10-17 at 12 17 54 PM" src="https://github.com/manojnegi07/social-external/assets/18699624/a3eba5c7-466d-45fc-9aba-ff42ea264609">

Or any other logic

**Comment by Anupriyabanger** [comment]
Seems like logic is added, as technology insights are highest in number
![image](https://github.com/manojnegi07/social-external/assets/109590553/fad6c02d-9367-4d6e-81bf-f34e9bad12c6)
