### ISSUE TITLE
Insights: while changing to grid type UI, shimmers must also be changed

### ISSUE THREAD

**Issue by technicalbirdVayuz** [manojnegi07/social-external#1163]
<img width="1440" alt="Screenshot 2023-10-17 at 12 19 23 PM" src="https://github.com/manojnegi07/social-external/assets/18699624/5b0794e1-f364-4cff-afd4-67d7ceb33d51">

**Comment by Anupriyabanger** [comment]
Not done
https://www.loom.com/share/921bb48109114b42a212f45c5f89d42e?sid=07143fbe-8346-422f-9e36-ec4d80ec6844
