### ISSUE TITLE
Insights: No data found must be in centre

### ISSUE THREAD

**Issue by technicalbirdVayuz** [manojnegi07/social-external#1166]
<img width="1439" alt="Screenshot 2023-10-17 at 12 22 10 PM" src="https://github.com/manojnegi07/social-external/assets/18699624/9b61be9d-24c9-4cce-a448-9984f3147762">

**Comment by rgnarok** [comment]
<img width="1223" alt="image" src="https://github.com/manojnegi07/social-external/assets/85341053/2aded373-786c-4b07-861b-b87d893058df">

Not fixed

**Comment by vayuzpriya** [comment]
@manojnegi07 fix the issue on grid view.
