### ISSUE TITLE
Add circle in place of pipe 

### ISSUE THREAD

**Issue by vayuzpriya** [manojnegi07/social-external#1168]
![image](https://github.com/manojnegi07/social-external/assets/81085431/e7329cf4-79ee-4711-9177-6c431a1893a9)

**Comment by Anupriyabanger** [comment]
@vayuzpriya ![image](https://github.com/manojnegi07/social-external/assets/109590553/4c247913-d25e-4d5b-af72-afdfed584759)

**Comment by vayuzpriya** [comment]
- [x] insight listing
- [x] insight detail 
- [x] auther listing

**Comment by vayuzpriya** [comment]
> @vayuzpriya ![image](https://private-user-images.githubusercontent.com/109590553/329148937-4c247913-d25e-4d5b-af72-afdfed584759.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTkxNDMsIm5iZiI6MTcxNTU5ODg0MywicGF0aCI6Ii8xMDk1OTA1NTMvMzI5MTQ4OTM3LTRjMjQ3OTEzLWQyNWUtNGQ1Yi1hZjcyLWFmZGZlZDU4NDc1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxMTE0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjU4ZTEyNTYwODBmYmNhNGRkMjZjOTZlMDJjMmI0ZGExODlkMTFmMTdmMjBkMTkxOTgxZGI2NWJjY2M4Mjg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KHHsfn1cL6hKRUc7Apy26EU5KtmXRQ_KJbOf8DIrIMU)

@Anupriyabanger pls share the issue here, why you reopen the issue

**Comment by milivayuz** [comment]
Still not circular in insight detail
<img width="708" alt="image" src="https://github.com/manojnegi07/social-external/assets/156641922/a7f049c3-eedf-4eac-a122-07750f4166b7">

**Comment by vayuzpriya** [comment]
make the profile pic same at all places

**Comment by rgnarok** [comment]
<img width="1398" alt="image" src="https://github.com/manojnegi07/social-external/assets/85341053/92daf6e5-5197-4c30-b839-99697eaaf186">

IT is not fixed for insight listing and detail working fine on author listing

**Comment by vayuzpriya** [comment]
Already discussed on call with Kush and Pointer closed.
