### ISSUE TITLE
There is no loading shimmer on category slider

### ISSUE THREAD

**Issue by manojnegi07** [manojnegi07/social-external#1181]
![image](https://github.com/manojnegi07/social-external/assets/92147060/f8417e3e-6031-46a9-a646-a7078658657a)

**Comment by Anupriyabanger** [comment]
Still not added
![Screenshot (350)](https://github.com/manojnegi07/social-external/assets/109590553/acb671d1-bc0b-4dd8-aedd-8c97668a121d)

**Comment by vayuzpriya** [comment]
@manojnegi07 shimmers added in code pls make it functional
