### ISSUE TITLE
Insights: See all articles in the bottom of More from Gaurav Kamboj (refer images) can be moved to top with something like view more

### ISSUE THREAD

**Issue by technicalbirdVayuz** [manojnegi07/social-external#1198]
See all articles seems like it will open all the articles there only but its not like this

**Comment by vayuzpriya** [comment]
adding in bottom but ui changed

**Comment by Anupriyabanger** [comment]
@vayuzpriya Fix the UI, this is not looking good, looks cluttered 
@manojnegi07 no need to show 12 articles as related, show maximum 4-5
![image](https://github.com/manojnegi07/social-external/assets/109590553/dd95a8bb-6ddb-441f-afe0-9b9f2753704d)
