### ISSUE TITLE
Create Insight > Summary page | UI issue when we insert multiple summary lines

### ISSUE THREAD

**Issue by Gaurav-Vayuz** [manojnegi07/social-external#1202]
![Uploading photo_2023-10-17_12-46-45.jpg…]()

**Comment by milivayuz** [comment]
<img width="146" alt="image" src="https://github.com/manojnegi07/social-external/assets/156641922/611c8306-fbec-4b80-96b5-88dc0354a31e">

still Issue with the UI Summary title is overlapping
