### ISSUE TITLE
Reaction emoji not loading on insight detail page

### ISSUE THREAD

**Issue by manojnegi07** [manojnegi07/social-external#1208]
![image](https://github.com/manojnegi07/social-external/assets/92147060/61c02956-18e9-4611-aeab-e0f83f422b3c)

**Comment by Anupriyabanger** [comment]
Not visible
![image](https://github.com/manojnegi07/social-external/assets/109590553/c6d594f1-e7a4-493b-8ef3-0409f396b80d)

**Comment by manojnegi07** [comment]
![image](https://github.com/manojnegi07/social-external/assets/92147060/8b846e01-ce5c-4571-92f4-8b349109606c)
