### ISSUE TITLE
Create Insight > Not able to (Select all) text

### ISSUE THREAD

**Issue by Gaurav-Vayuz** [manojnegi07/social-external#1209]
https://github.com/manojnegi07/social-external/assets/127476406/fed16402-d5eb-4b8e-ba0b-590fcd1dd568

**Comment by manojnegi07** [comment]
IT is because of the editor. it has different section for each heading and paragraph

**Comment by Anupriyabanger** [comment]
> IT is because of the editor. it has different sections for each heading and paragraph
@manojnegi07 please add a solution here

**Comment by manojnegi07** [comment]
@Anupriyabanger  for that we need to change the editor here. 
please suggest the editor

**Comment by Anupriyabanger** [comment]
@Anupriyabanger cannot be done as the editor is applied on each line separately, making it impossible to select the entire text at once
