### ISSUE TITLE
Add suggestion in SEO details 

### ISSUE THREAD

**Issue by vayuzpriya** [manojnegi07/social-external#1215]
![image](https://github.com/manojnegi07/social-external/assets/81085431/c91c1b3e-804d-470e-9d4b-33dd009992d9)

**Comment by manojnegi07** [comment]
@Anupriyabanger  please update text

**Comment by Anupriyabanger** [comment]
https://github.com/manojnegi07/social-external/issues/1515 Duplicate issue
