### ISSUE TITLE
Align bookmark icon with 3 dots and can we add this option where the 3 dots will only be visibkle when i hover on that byte like we have in insights listing

### ISSUE THREAD

**Issue by rgnarok** [manojnegi07/social-external#1237]
<img width="347" alt="image" src="https://github.com/manojnegi07/social-external/assets/85341053/aa5c3bdc-ec68-4a5d-9e67-50032d45796c">

**Comment by vayuzpriya** [comment]
- [ ] Align bookmark icon with 3 dots
- [ ] can we add this option where the 3 dots will only be visibkle when i hover on that byte like we have in insights listing

**Comment by vayuzpriya** [comment]
2nd issue reported on other issue . https://github.com/manojnegi07/social-external/issues/1347
first one is done.
