### ISSUE TITLE
MS edge> Byte> If i am expanding TC details, then i am not able to view the last person

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#1250]
Not able to scroll also
![image](https://github.com/manojnegi07/social-external/assets/109590553/534d6648-07d1-4e68-a2fb-a4d33f2694fd)

**Comment by vayuzpriya** [comment]
![image](https://github.com/manojnegi07/social-external/assets/81085431/0d913d71-ec59-47ed-9231-f6565dd78130)
fixed
