### ISSUE TITLE
Cluttered Byte Listing > No post saperation here > Looking like on whole post

### ISSUE THREAD

**Issue by manojnegi07** [manojnegi07/social-external#1253]
![image](https://github.com/manojnegi07/social-external/assets/92147060/96ca0747-23c2-45ed-a2d5-baa622e95264)

**Comment by vayuzpriya** [comment]
in this post which post you are mention here because first byte is single post where you shared someone else byte

**Comment by manojnegi07** [comment]
![image](https://github.com/manojnegi07/social-external/assets/92147060/bde9125f-7fde-4998-ac3b-49abf9b1eaba)
please do something like this

**Comment by vayuzpriya** [comment]
![image](https://github.com/manojnegi07/social-external/assets/81085431/7ed84e89-16f2-4dc2-bedc-cb67f8c59474)
