### ISSUE TITLE
Wrong Bookmarked icon. we can use different color for that. grey is not looking good here

### ISSUE THREAD

**Issue by manojnegi07** [manojnegi07/social-external#1255]
![image](https://github.com/manojnegi07/social-external/assets/92147060/85bad7f6-6c2f-480d-80e7-4c583f2f43f1)

**Comment by vayuzpriya** [comment]
![image](https://github.com/manojnegi07/social-external/assets/81085431/247191bd-776f-4bb3-873f-976a40b94f46)
