### ISSUE TITLE
Signout Button and Social is in  Wrong Place !

### ISSUE THREAD

**Issue by Sujayvayuz07** [manojnegi07/social-external#1275]
![sign](https://github.com/manojnegi07/social-external/assets/134473545/2fbfeebb-d4e8-425c-a2c0-b323837ebe0e)

**Comment by vayuzpriya** [comment]
It's changed.

**Comment by vayuzpriya** [comment]
Need to work on Functional Part @manojnegi07

**Comment by vayuzpriya** [comment]
![image](https://github.com/manojnegi07/social-external/assets/81085431/c17d76c3-c2d0-457d-9c19-431158e5626e)
fixed
