### ISSUE TITLE
New Byte Not loading on clicking of new Bytes

### ISSUE THREAD

**Issue by manojnegi07** [manojnegi07/social-external#1331]

**Comment by Anupriyabanger** [comment]
Still same

**Comment by Anupriyabanger** [comment]
Not working properly: https://www.loom.com/share/18e2785d3c574b6b90d6b3c394f05802

**Comment by manojnegi07** [comment]
https://github.com/manojnegi07/social-external/assets/92147060/97bb3ca2-4cc9-400c-929f-b7cfc12fd167
