### ISSUE TITLE
Not able to tag anyone in last of byte

### ISSUE THREAD

**Issue by vayuzpriya** [manojnegi07/social-external#1337]
![image](https://github.com/manojnegi07/social-external/assets/81085431/4ed73fd6-b52e-4cd6-ae6b-2d8a7f1d0fad)

**Comment by manojnegi07** [comment]
![image](https://github.com/manojnegi07/social-external/assets/92147060/8585fb99-a0f2-440c-9b81-d70bbd4f8e86)
