### ISSUE TITLE
Event rating modal > starts were in reverse order and color issue

### ISSUE THREAD

**Issue by VayuzBidyut** [manojnegi07/social-external#1349]
![2023-10-31_120219](https://github.com/manojnegi07/social-external/assets/78781245/37858981-c754-44d4-9ae8-4c14ab1d10f3)

**Comment by Anupriyabanger** [comment]
@bidyut-majumdar still not the right format ![image](https://github.com/manojnegi07/social-external/assets/109590553/964fe1a7-fbc0-4673-bf6f-8750cb047bc6)

**Comment by vayuzpriya** [comment]
UI Issue fixed, functional pending.
