### ISSUE TITLE
text on bye coming wrong

### ISSUE THREAD

**Issue by vayuzpriya** [manojnegi07/social-external#1357]
![image](https://github.com/manojnegi07/social-external/assets/81085431/82e331ed-abaa-4e74-903c-9f110202dcca)
Priya shared sujay byte but in text  showing both shared byte

**Comment by Anupriyabanger** [comment]
Issue not resolved
![image](https://github.com/manojnegi07/social-external/assets/109590553/29895438-e2ce-4881-a958-9a0393386fc6)
