### ISSUE TITLE
in 3  dot i hav enot option to share byte but from bottom i can share my byte

### ISSUE THREAD

**Issue by vayuzpriya** [manojnegi07/social-external#1368]
![image](https://github.com/manojnegi07/social-external/assets/81085431/c5997230-d118-4feb-8639-6627d97e0e8f)

**Comment by manojnegi07** [comment]
![image](https://github.com/manojnegi07/social-external/assets/92147060/cfa0e19d-324e-4c15-b104-a84b9790bf62)

It will not be available on private byte
