### ISSUE TITLE
ios > web > mobile view > functional 

### ISSUE THREAD

**Issue by rajasrivastava101** [manojnegi07/social-external#1392]
![image](https://github.com/manojnegi07/social-external/assets/129847373/ddaa25e3-2855-4442-9bff-29f67e67717b)
![Uploading image.png…]()

When I am going to add a comment, the posted picture is not displayed as it was posted.

**Comment by vayuzpriya** [comment]
@rajasrivastava101 pls check and let me know if issue occurs
