### ISSUE TITLE
Detail Byte > Refer this Byte by Sujoy, see the original Byte and then the detail one.

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#1426]
the media content is all over the place.
Detail Byte:
![image](https://github.com/manojnegi07/social-external/assets/109590553/2f70d331-4c0f-445a-bfb1-615ab4be516f)

**Comment by manojnegi07** [comment]
@vayuzpriya its not the Functional Issue its UI issue 
https://social.vayuz.com/byte/ZmVlZF9pZF8xNzAwMzMxNTM0MTI3
