### ISSUE TITLE
Byte> Quiz in Byte

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#1439]
![image](https://github.com/manojnegi07/social-external/assets/109590553/a9108578-83f1-4301-8436-e9f854fa3442)
![image](https://github.com/manojnegi07/social-external/assets/109590553/6adf9256-a2c3-40bf-a987-572e0a40ce2d)
![image](https://github.com/manojnegi07/social-external/assets/109590553/5df54110-b2d1-441e-ace0-e0deff5254b4)
![image](https://github.com/manojnegi07/social-external/assets/109590553/97904e9d-5937-43f9-921c-50cccbf62ee1)
![image](https://github.com/manojnegi07/social-external/assets/109590553/b54123e6-cb9f-4b3b-89d0-d83b8733134e)

**Comment by manojnegi07** [comment]
Functional - 56 Hrs
