### ISSUE TITLE
Hashtags on shoutout content sections doesn't work  (clicked or redirect us to hashtag specific listing results)

### ISSUE THREAD

**Issue by VayuzBidyut** [manojnegi07/social-external#1457]
![2023-12-17_165102](https://github.com/manojnegi07/social-external/assets/78781245/676d6fe0-e383-4d6f-b1c8-12c361f6977a)

**Comment by Anupriyabanger** [comment]
Not working, it is treating it as plain text and not as a Hashtag
![image](https://github.com/manojnegi07/social-external/assets/109590553/4805f88b-f7ab-4326-879d-7a27fa8bb07c)

**Comment by milivayuz** [comment]
clicking on hashtag it should go into the search and shows me all the stuff with that tag name

**Comment by manojnegi07** [comment]
Currently hashtag based search is not available . on listing it will filter out the post with the perticular hashtags
