### ISSUE TITLE
Check the placeholder text getting coinciding with the label

### ISSUE THREAD

**Issue by rgnarok** [manojnegi07/social-external#1469]
<img width="1107" alt="image" src="https://github.com/manojnegi07/social-external/assets/85341053/f987d8ec-6d35-4804-8de0-825e7d865c57">

**Comment by milivayuz** [comment]
<img width="766" alt="image" src="https://github.com/manojnegi07/social-external/assets/156641922/931824b5-63c3-4993-b3c6-8d3f742c9e17">

Still facing the same issue
