### ISSUE TITLE
Insight> Edit> On clicking the tabs, users should be able to click and reach to the selected tab

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#1480]
![image](https://github.com/manojnegi07/social-external/assets/109590553/36304408-d09e-43c9-b65c-af8dda376e4f)

**Comment by manojnegi07** [comment]
this cant be done. forms have validations you can not just jumpp into other forms

**Comment by Anupriyabanger** [comment]
@manojnegi07 we can do this for the edit form, as the insight was already published.
