### ISSUE TITLE
Web > Request

### ISSUE THREAD

**Issue by milivayuz** [manojnegi07/social-external#1511]
On accepting a Friend request, pop up shows the connection removed.

**Comment by manojnegi07** [comment]
![image](https://github.com/manojnegi07/social-external/assets/92147060/13ce62b6-2e3e-4b63-bd0d-b39f4677563c)
![image](https://github.com/manojnegi07/social-external/assets/92147060/21d6ae0e-9e95-4101-86bb-7e9be9a98a8d)

working fine
