### ISSUE TITLE
Byte> Shout out> Shout out not working properly

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#1512]
If i have created a shout out previously and not published it, and close the created box and then again open, it shows the same detail and i cannot even edit the details
https://www.loom.com/share/61d64dee129544178f6517c71c0072eb?sid=f26a216b-5643-4118-b59a-23ffbd8b2b19

**Comment by manojnegi07** [comment]
![image](https://github.com/manojnegi07/social-external/assets/92147060/6a86614d-c545-481d-b067-ff27ff77dd78)
UI Fixed

**Comment by rgnarok** [comment]
https://drive.google.com/file/d/1NZy11N2eMFe_rxJnCQLvkyFcCjaOxEOs/view?usp=sharing
Not fixed

**Comment by milivayuz** [comment]
still the same issue

**Comment by manojnegi07** [comment]
Please clear cache before testing
