### ISSUE TITLE
Insights> Add polls on insight detail

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#1514]
Show the polls should be there on every insights detail page at the end of every insight for the readers to rate the insight
Use the following rating parameters:

1. Demonstrates Excellence
2.  Exceeds Expectation
3.  Meets Expectation
4.  Needs Improvement
![image](https://github.com/manojnegi07/social-external/assets/109590553/d3259a13-1cac-48aa-9474-90ef0b852927)
On selecting the Demonstrates Excellence: ![image](https://github.com/manojnegi07/social-external/assets/109590553/907ecf6d-b122-43b2-bff8-8e690717f5c2)
On selecting the Needs Improvement:
![image](https://github.com/manojnegi07/social-external/assets/109590553/4ac63d67-4b50-4cb1-be48-31c22afb9c8e)

**Comment by manojnegi07** [comment]
Functional Time - 24 hrs

**Comment by vayuzpriya** [comment]
5hr approx

**Comment by vayuzpriya** [comment]
Code added in  "insight-detail.svelte"page @manojnegi07

**Comment by rgnarok** [comment]
<img width="915" alt="image" src="https://github.com/manojnegi07/social-external/assets/85341053/fddbfb0e-a962-4693-ae7b-be85e0f0edb8">

Can we just add rating with text which is understood by everyone the rating is not layman and also can we have colour bands like we have in reference

**Comment by manojnegi07** [comment]
@Anupriyabanger  please provide text
