### ISSUE TITLE
icon are not aligned

### ISSUE THREAD

**Issue by vayuzpriya** [manojnegi07/social-external#1527]
![image](https://github.com/manojnegi07/social-external/assets/81085431/b1938c98-38b5-402b-bfb8-ab0f8791bdbd)

**Comment by rgnarok** [comment]
<img width="1128" alt="image" src="https://github.com/manojnegi07/social-external/assets/85341053/e0311398-6c3e-45b6-a783-b23951974280">

Check the GIF icon it is still not aligned
