### ISSUE TITLE
There is no option of other to add a text for the reason if it is not in the list 

### ISSUE THREAD

**Issue by rgnarok** [manojnegi07/social-external#1535]
<img width="986" alt="image" src="https://github.com/manojnegi07/social-external/assets/85341053/7956eaef-78bd-4487-ad8a-6e4df942af54">

**Comment by rgnarok** [comment]
https://drive.google.com/file/d/1NZy11N2eMFe_rxJnCQLvkyFcCjaOxEOs/view?usp=sharing
Not fixed

**Comment by vayuzpriya** [comment]
UI Is already added @manojnegi07 why you are not impliment this
