### ISSUE TITLE
Social Bookmark

### ISSUE THREAD

**Issue by manojnegi07** [manojnegi07/social-external#172]
# Details 
Bookmark issues: 
1.Notes added are not visible on the bookmark listing page
2.My Bookmark> duplicate categories are created.
3. My bookmark> if any bookmark is removed from the listing page, the removed post is opening.
4.Create bookmark> Private category text is not clickable.
5. No option to deleted previous category.
6.Create Bookmark> Bookmarked post is visible on the homepage and Bookmark page is empty.
7.Bookmark listing page> No back option available for selecting previous category 
8.Bookmark listing page> If multiple categories are created then not able to see the "All" category option.

| <a href="https://drive.google.com/open?id=12AfZgB1B0vc8tBO7AERGtAqp8xg4OIAX" target="_blank">https://drive.google.com/open?id=12AfZgB1B0vc8tBO7AERGtAqp8xg4OIAX</a> 
<a href="https://drive.google.com/open?id=1aDF82mGHbO_3bCp6YtVA59yK7PQjOdQK" target="_blank">https://drive.google.com/open?id=1aDF82mGHbO_3bCp6YtVA59yK7PQjOdQK</a> 
<a href="https://drive.google.com/open?id=1fjjiaIO147z4xR93RRdGyydhOfoAOjLH" target="_blank">https://drive.google.com/open?id=1fjjiaIO147z4xR93RRdGyydhOfoAOjLH</a> 
<a href="https://drive.google.com/open?id=1EUEtNaorbkw1Wr_XPaEIif5LA7yttg99" target="_blank">https://drive.google.com/open?id=1EUEtNaorbkw1Wr_XPaEIif5LA7yttg99</a> 
<a href="https://drive.google.com/open?id=1rgc8l2lbR-Trja6zxovmxa_uXicxXW64" target="_blank">https://drive.google.com/open?id=1rgc8l2lbR-Trja6zxovmxa_uXicxXW64</a> 

<strong>Solution :NA</strong>

**Comment by vayuzpriya** [comment]
1.Notes added are not visible on the bookmark listing page  - **option for showing notes added** 
2.My Bookmark> duplicate categories are created. - **Functional**
3. My bookmark> if any bookmark is removed from the listing page, the removed post is opening. - **Functional**
4.Create bookmark> Private category text is not clickable. - **Functional**
5. No option to deleted previous category. - **Option Added in manage category page** **- Functional Left**
6.Create Bookmark> Bookmarked post is visible on the homepage and Bookmark page is empty. - **Functional**
7.Bookmark listing page> No back option available for selecting previous category  - **you can select category from top header why you need back option here**
8.Bookmark listing page> If multiple categories are created then not able to see the "All" category option - **Added**

**Comment by vayuzpriya** [comment]
issue duplicate with #177
