### ISSUE TITLE
Edit Byte | background color byte edit is not correct on mobile 

### ISSUE THREAD

**Issue by vayuzpriya** [manojnegi07/social-external#196]
- we can edit the bg color also 
- we can edit the privacy option 
- show edited text in edited byte / comment

**Comment by manojnegi07** [comment]
we can edit the bg color also
we can edit the privacy option
show edited text in edited byte / comment   **- Done**

**Comment by Anupriyabanger** [comment]
not showing edited text in an edited byte. @manojnegi07
