### ISSUE TITLE
When we click on edit and then click on emojies keyboard is open with emojis 

### ISSUE THREAD

**Issue by vayuzpriya** [manojnegi07/social-external#197]
- Hide the Keyboard
- Emojis is not properly come.

**Comment by manojnegi07** [comment]
Removed editor emoji from mobile. Show that we can use mobile keyboard emoji in it

**Comment by Anupriyabanger** [comment]
If i click on emoji keyboard, and then i don't want to use any emoji, I should be able to click outside emoji table and go back to create byte screen. @manojnegi07

**Comment by manojnegi07** [comment]
it is you mobile functionality right now i cant do anything
