### ISSUE TITLE
byte> report byte> after canceling to report a byte, post is still removed from the feed

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#209]

**Comment by manojnegi07** [comment]
It will get removed if you continue from first step. and then press cancel in second step. because second step is to remove connection

**Comment by Anupriyabanger** [comment]
@manojnegi07 In the report modal please add a checkbox stating "please hide the byte from my feed", so that only upon checking the box the byte gets hidden from feed, else not.
