### ISSUE TITLE
Profile>Add employee details>check description

### ISSUE THREAD

**Issue by Ahlam000** [manojnegi07/social-external#22]
1. dropdown only showing select option either it should be dropdown with prefilled list or input box 
2. Add employee details field it should be restricted to some limit of characters i can enter inifiniter characters
3. No able to differentiate between required and optional fields required field should have asterick mark

**Comment by manojnegi07** [comment]
1-dropdown only showing select option either it should be dropdown with prefilled list or input box - **It is a free input with search options. so by default it will not have any value. but once user enter keys here. it will search for result and list here but if user dont want to select them then it can use the written value only.So there is no need for prefilled values here**

2. Add employee details field it should be restricted to some limit of characters i can enter inifiniter characters --- **Added limit of 200**
No able to differentiate between required and optional fields required field should have asterick mark - **Done**

**Comment by Anupriyabanger** [comment]
@manojnegi07 Please add limit to:
1. Company 
2. Job title
3. City
![image](https://user-images.githubusercontent.com/109590553/202399977-6965c2d0-5c8f-43d4-8ea8-c6e1b31879b4.png)
