### ISSUE TITLE
Create Byte >> Potrait image collage layout, please check linkedin in our case the images are getting cut but in the case of linkedin all the images are coming properly , alos our 1 and 2 image collage is correct please correct 3, 4 and 5 image collage

### ISSUE THREAD

**Issue by rgnarok** [manojnegi07/social-external#220]
<img width="811" alt="image" src="https://user-images.githubusercontent.com/85341053/186091473-7488fb12-31d8-40cb-8ecb-95945f49b139.png">
<img width="674" alt="image" src="https://user-images.githubusercontent.com/85341053/186091726-d154aa2b-9e43-426c-9341-741454eca04b.png">

**Comment by vayuzpriya** [comment]
structure change norw in slidr view
