### ISSUE TITLE
Create Byte >> Landscape images layout need to be set propwerly for mor clear visiblity check how linkedin set this

### ISSUE THREAD

**Issue by rgnarok** [manojnegi07/social-external#221]
<img width="592" alt="image" src="https://user-images.githubusercontent.com/85341053/186095273-f27e9cab-f104-45c1-85ed-83fc0df3b4e1.png">
<img width="741" alt="image" src="https://user-images.githubusercontent.com/85341053/186095301-445d583b-b849-4808-90d6-665308220942.png">
<img width="722" alt="image" src="https://user-images.githubusercontent.com/85341053/186097990-1bb5024e-320e-4035-ab60-dce74589b35d.png">
<img width="611" alt="image" src="https://user-images.githubusercontent.com/85341053/186098072-165d6b37-4290-4949-a2a6-c4c4f4e0abe3.png">
<img width="579" alt="image" src="https://user-images.githubusercontent.com/85341053/186100045-f2f99500-8928-491f-9ae0-cc7cb069d299.png">
<img width="756" alt="image" src="https://user-images.githubusercontent.com/85341053/186100148-1d318781-3332-4417-853b-8714f840f82b.png">

**Comment by vayuzpriya** [comment]
image structure was changed in slider view so need for this structure
