### ISSUE TITLE
Create Byte>> No option to make polls public or Private they are only becoming for my connections

### ISSUE THREAD

**Issue by rgnarok** [manojnegi07/social-external#227]
<img width="715" alt="image" src="https://user-images.githubusercontent.com/85341053/186112581-2df90cb6-c46f-4ec8-8c8c-90830338138e.png">
<img width="731" alt="image" src="https://user-images.githubusercontent.com/85341053/186112717-b3f29e49-1341-4794-98b4-a51202d04935.png">

**Comment by manojnegi07** [comment]
@rgnarok  added public or connection only in privacy. because there no use of posting a poll private.

**Comment by Anupriyabanger** [comment]
done.
