### ISSUE TITLE
Byte >> There should be a charracter limit to the byte, for writing thinking of blog size  user must user news and we must show a toast for this suggesting to use news

### ISSUE THREAD

**Issue by rgnarok** [manojnegi07/social-external#237]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/85341053/186124877-6537879c-bdb9-468b-82e8-0af4f237b310.png">

**Comment by manojnegi07** [comment]
@rgnarok  we can have discussion on it

**Comment by manojnegi07** [comment]
@rgnarok  i dont think we should restrict user here .  Moving it to discussion .

**Comment by Anupriyabanger** [comment]
@manojnegi07 Please add limit of 500 characters for creating byte

**Comment by manojnegi07** [comment]
Fixed ti to 1000
