### ISSUE TITLE
Byte >> Share can be allowed without adding any caption to it please remove this validation

### ISSUE THREAD

**Issue by rgnarok** [manojnegi07/social-external#238]
<img width="884" alt="image" src="https://user-images.githubusercontent.com/85341053/186127161-76ee5c24-49eb-4003-bf06-538c31383496.png">

**Comment by Anupriyabanger** [comment]
<img width="432" alt="image" src="https://user-images.githubusercontent.com/109590553/187161912-b9433b88-5b00-4c36-9d10-bcd97e0dbb95.png">

blank space should not appear in case no caption is shared.

**Comment by Anupriyabanger** [comment]
Issue not resolved. I had to type something then the share button appears but not otherwise  @manojnegi07 
![image](https://user-images.githubusercontent.com/109590553/201057586-c4c2cd5a-3072-4b5f-956c-7e9f0b6a8794.png)
