### ISSUE TITLE
Create Byte >> Not generating meta details when we write www.domain.com the same way it is done in teams 

### ISSUE THREAD

**Issue by rgnarok** [manojnegi07/social-external#244]
<img width="935" alt="image" src="https://user-images.githubusercontent.com/85341053/186130050-358dc5fc-14ad-4859-b321-d9cf3c3a4b76.png">
<img width="809" alt="image" src="https://user-images.githubusercontent.com/85341053/186130106-b92d1925-e352-49d7-a2c7-6fef24ad6af0.png">

**Comment by Anupriyabanger** [comment]
done.
