### ISSUE TITLE
Byte >> On comment add a tag creator since i am the creator of this post and i am adding the comment other should get this info

### ISSUE THREAD

**Issue by rgnarok** [manojnegi07/social-external#247]
<img width="517" alt="image" src="https://user-images.githubusercontent.com/85341053/186133466-18ce256c-56af-493e-b8d5-49884aaadda7.png">

**Comment by manojnegi07** [comment]
@rgnarok  what is the need of this

**Comment by rgnarok** [comment]
@manojnegi07  sometimes people with same name and id but not the original account holder comments and this may cause a confusion between the users

**Comment by Anupriyabanger** [comment]
done.
