### ISSUE TITLE
Byte >> Add charracter limit to comments, dont allow people to write stories in comment section

### ISSUE THREAD

**Issue by rgnarok** [manojnegi07/social-external#248]
<img width="474" alt="image" src="https://user-images.githubusercontent.com/85341053/186133838-44fe80ff-a732-4248-96cf-cf1bcebdef17.png">

**Comment by manojnegi07** [comment]
Limit set to 150 characters

**Comment by Anupriyabanger** [comment]
<img width="693" alt="image" src="https://user-images.githubusercontent.com/109590553/187159958-4c20f457-f5e3-4c8d-9119-7a6b50b98846.png">
 
Issue not resolved.
