### ISSUE TITLE
My Bookmarks >>clicking on   Add bookmark  shows this screen >> check SS

### ISSUE THREAD

**Issue by Ahlam000** [manojnegi07/social-external#259]
<img width="1440" alt="Screenshot 2022-08-24 at 5 15 31 PM" src="https://user-images.githubusercontent.com/101115620/186410435-b7fa2aa6-2e8a-4096-89ef-ccbf55aec388.png">

**Comment by manojnegi07** [comment]
Fixed the character limit in category .
