### ISSUE TITLE
News>share

### ISSUE THREAD

**Issue by atul-gautam-au6** [manojnegi07/social-external#26]
![Screenshot_2022-07-06_18-04-28](https://user-images.githubusercontent.com/58418713/177551661-b16f05cc-4fa8-4648-bdfc-c7def7f1be97.png)

cancel icon hover text should be on single line

**Comment by vayuzpriya** [comment]
Ui Design Change so this option is not added. 
reported on it as a another issue.

**Comment by vayuzpriya** [comment]
https://github.com/manojnegi07/social-external/issues/1526
