### ISSUE TITLE
Byte >>  Typing Cursor is not visible in dark mode when i click on the text area

### ISSUE THREAD

**Issue by rgnarok** [manojnegi07/social-external#269]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/85341053/186589107-43c8e3c3-e801-4459-9145-06b187fe5667.png">

**Comment by vayuzpriya** [comment]
When you click it's visible @rgnarok

**Comment by vayuzpriya** [comment]
![image](https://github.com/manojnegi07/social-external/assets/81085431/4cbd50ab-4e87-4259-8e9b-259a5101c7be)
done
