### ISSUE TITLE
Create Byte >> Interchange the confirm and cancel button as it is not correct 

### ISSUE THREAD

**Issue by rgnarok** [manojnegi07/social-external#272]
<img width="887" alt="image" src="https://user-images.githubusercontent.com/85341053/186590374-b499a8d0-b52a-4e16-83f7-0fc5c7c1ae00.png">

**Comment by Anupriyabanger** [comment]
not done.

**Comment by Anupriyabanger** [comment]
<img width="532" alt="image" src="https://user-images.githubusercontent.com/109590553/188794448-052dc6ad-42f6-458f-9f9f-40b28134767e.png">

@vayuzpriya

**Comment by vayuzpriya** [comment]
![Screenshot from 2022-09-08 11-17-17](https://user-images.githubusercontent.com/81085431/189043994-b9c9d224-0db2-491b-a8f2-9d1970022d48.png)
