### ISSUE TITLE
Byte >> Like 

### ISSUE THREAD

**Issue by rgnarok** [manojnegi07/social-external#275]
<img width="356" alt="image" src="https://user-images.githubusercontent.com/85341053/186595414-e73d319b-0eb3-4e1b-b74a-3935693d3541.png">
<img width="831" alt="image" src="https://user-images.githubusercontent.com/85341053/186595454-8d81b30a-1d5a-4291-a2d3-720aa722f2ba.png">
The like count is 2 but it is showing 1 and it is taking time to get updated to correct count

**Comment by manojnegi07** [comment]
Like functionality is fine. It happens when you hit like from local, heroku, live.

**Comment by Anupriyabanger** [comment]
done.
