### ISSUE TITLE
Byte Detail >> Names not coming up in comment or reply in dark mode and the suggestion bar is also coming white 

### ISSUE THREAD

**Issue by rgnarok** [manojnegi07/social-external#278]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/85341053/186600285-42af408b-d254-422e-86af-5766a020a107.png">

**Comment by Anupriyabanger** [comment]
<img width="317" alt="image" src="https://user-images.githubusercontent.com/109590553/188566003-0e792c06-047d-4443-b7ef-b61ae6c5cb36.png">

Issue not resolved.

**Comment by rgnarok** [comment]
<img width="501" alt="image" src="https://user-images.githubusercontent.com/85341053/203311948-6dad9ff8-ff8b-4ac9-a906-52bd791e3894.png">

<img width="382" alt="image" src="https://user-images.githubusercontent.com/85341053/203312313-90429be7-b289-4774-9d06-b2a3ce87f5a7.png">

both on web and mobile view
@Anupriyabanger
