### ISSUE TITLE
Byte detail >> Add show more and show less when the comment and reply are getting more and more so as o reduce the  scroll right now it is working when i refresh the page make it reactive

### ISSUE THREAD

**Issue by rgnarok** [manojnegi07/social-external#284]
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/85341053/186605778-1a1f4df9-756b-44d6-a413-ca2369387440.png">

**Comment by manojnegi07** [comment]
pagination is there. but for continues comment i didn't added it
