### ISSUE TITLE
Byte >> On light theme it is still showing it black and also the icons are not there as we have on the web 

### ISSUE THREAD

**Issue by rgnarok** [manojnegi07/social-external#294]
![image](https://user-images.githubusercontent.com/85341053/186618362-154e64d1-df07-4f50-b554-b3bb4ba243da.png)

**Comment by vayuzpriya** [comment]
@rgnarok  we are not keeping icons on bottom sheet, 
and in light or dark in both case bottom sheet is dark.

**Comment by vayuzpriya** [comment]
UI Changed
