### ISSUE TITLE
Profile>Add cetificate>check description

### ISSUE THREAD

**Issue by Ahlam000** [manojnegi07/social-external#30]
1. no character limit on certificate name/institute name
2. required field should have asterick mark in add certification also

**Comment by Anupriyabanger** [comment]
@manojnegi07 Issue 1 is not resolved.
Please add a limit of 50 Characters. 
![image](https://user-images.githubusercontent.com/109590553/202398688-7e420e6b-9d4a-4dfe-9201-0f337edd2de4.png)
