### ISSUE TITLE
Create Byte > Privacy > Update/Cancel button is not visible from at bottom as its not clear that we need to scroll down

### ISSUE THREAD

**Issue by bidyut-majumdar** [manojnegi07/social-external#307]
![Screenshot_20220902-123338_Chrome](https://user-images.githubusercontent.com/78781245/188118603-89ce8b1d-9915-4250-a951-989ad48573ca.jpg)

**Comment by Anupriyabanger** [comment]
issue not resolved. @vayuzpriya
