### ISSUE TITLE
News > Delete comment > toast message has unusual padding

### ISSUE THREAD

**Issue by VayuzBidyut** [manojnegi07/social-external#309]
![2022-09-02_155127](https://user-images.githubusercontent.com/78781245/188119548-5ba9ba86-fd3a-41c9-90b6-5cefc3f9efff.png)

**Comment by vayuzpriya** [comment]
Not able to delete comment 
![image](https://github.com/manojnegi07/social-external/assets/81085431/c289b7fa-a248-4bbd-96f3-1c8d6f7585c4)

**Comment by vayuzpriya** [comment]
![image](https://github.com/manojnegi07/social-external/assets/81085431/ad66cc96-5fe0-4a5f-9284-baa51d01eca5)
comment toast message is correct

**Comment by vayuzpriya** [comment]
![image](https://github.com/manojnegi07/social-external/assets/81085431/154ffb49-42ac-4f3a-a04a-bb0b987a2dd5)
