### ISSUE TITLE
Byte > Please disable automatic video play on the platform 

### ISSUE THREAD

**Issue by bidyut-majumdar** [manojnegi07/social-external#319]
As whenever it is opened even if the video is posted some 6 - 7 bytes ago it starts playing with sound resulting bad experience

**Comment by Anupriyabanger** [comment]
Automatic video play is disabled but if we move the cursor the video automatically pauses. Once a video is played, it should be paused only when we completely scroll down to the next post or we pause the video manually. @manojnegi07

**Comment by bidyut-majumdar** [comment]
Still the same issue :

Use case : Currently Ankit has shared a youtube video, upon opening byte it doesn't automatically play at first . Now open news section , then click on byte to open Byte again, the video will start playing automatically .
