### ISSUE TITLE
Byte> No change on read more and less 

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#347]
Character limit is not fixed, 
![image](https://user-images.githubusercontent.com/109590553/200261693-f9e383d5-ee7d-4601-addb-e997a9ddea8e.png)
![image](https://user-images.githubusercontent.com/109590553/200261788-a2b1c54c-fc51-4705-af8f-fb17b0e80ddc.png)

**Comment by Anupriyabanger** [comment]
Not resolved. @manojnegi07 
![image](https://user-images.githubusercontent.com/109590553/201034942-60394ec5-1f85-4d51-9001-5fdd02bfc434.png)
![image](https://user-images.githubusercontent.com/109590553/201035024-82cd2251-e1d7-46c0-a205-eb0963898f29.png)

**Comment by Anupriyabanger** [comment]
@manojnegi07 Issue not resolved.
![image](https://user-images.githubusercontent.com/109590553/202679923-9c184a75-66f5-48e9-99d4-218c95d4bada.png)
![image](https://user-images.githubusercontent.com/109590553/202679991-2fac3c8a-bc4c-487e-8a52-ed325150fe51.png)

**Comment by manojnegi07** [comment]
@Anupriyabanger  it is according to the number of lines not number of characters. If we make it number of character wise then if user type one character in one line and then press enter then it will break the UI so that is why initially i am showing 8 to 9 lines and then it is in show more

**Comment by manojnegi07** [comment]
![image](https://user-images.githubusercontent.com/92147060/204453812-742f13f4-6e63-4b90-9118-d33fa07d9c91.png)
