### ISSUE TITLE
Byte> Private post should not be able to share

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#348]
![image](https://user-images.githubusercontent.com/109590553/200263952-7435712e-6aef-441a-a18b-75579993fa43.png)
![image](https://user-images.githubusercontent.com/109590553/200271437-9ce6a1a3-e325-43c5-9c35-8038ec4ad990.png)

**Comment by Anupriyabanger** [comment]
The privacy status of the other user changed. I shared only to connection post as a private post but after sharing the status of both changed.
![image](https://user-images.githubusercontent.com/109590553/201033132-de10c4eb-657d-4b6b-b92b-64b2715c2a65.png)

**Comment by manojnegi07** [comment]
Again both issues are not related
