### ISSUE TITLE
Create Byte> preview video not visible

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#351]
![image](https://user-images.githubusercontent.com/109590553/200274725-8c793e0d-ed40-4043-a3af-d1e00c8cd25c.png)

**Comment by Anupriyabanger** [comment]
video not uploading, not able to check the issue.
![image](https://user-images.githubusercontent.com/109590553/203006344-cdc88115-1083-44c7-81e4-6265f121cddf.png)

**Comment by rgnarok** [comment]
<img width="776" alt="image" src="https://github.com/manojnegi07/social-external/assets/85341053/085965db-21b9-4892-ab78-a7b15afd2841">

This is how it is coming please fix

**Comment by vayuzpriya** [comment]
![image](https://github.com/manojnegi07/social-external/assets/81085431/e048aa46-d000-46e6-9843-589270265364)
