### ISSUE TITLE
Search > by default is it showing people category, when result is other category then that category should be active 

### ISSUE THREAD

**Issue by jagdish-vayuz** [manojnegi07/social-external#36]
when i searched 'nother' it shows not result found and people tab is active, and news(1) but not active

**Comment by manojnegi07** [comment]
Yes because in current flow people tab will be active

**Comment by Anupriyabanger** [comment]
@manojnegi07 please make the tab active which has the related content.

**Comment by manojnegi07** [comment]
Need to change the current flow of search.  We need to discuss this @Anupriyabanger
