### ISSUE TITLE
Profile > Certification details > There is no option to add location while adding certification but it is showing in the Listing > Check Screenshot 

### ISSUE THREAD

**Issue by Arushiv13** [manojnegi07/social-external#380]
![Screenshot (287)](https://user-images.githubusercontent.com/94099426/200775247-ef0ff8fa-5947-4117-ab63-413166b31e02.png)
![Screenshot (288)](https://user-images.githubusercontent.com/94099426/200775265-9a890e2b-31db-4148-84e3-d91d560ea5e0.png)
mano

**Comment by manojnegi07** [comment]
Removed location icon
