### ISSUE TITLE
Deleted post is accessible from notification listing

### ISSUE THREAD

**Issue by bidyut-majumdar** [manojnegi07/social-external#39]
The mentioned post was deleted, but I can see and access the post from the notification.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/78781245/177956422-9de96bc4-6653-4f9c-970d-5d7023f5dee1.png)

![2022-07-08_142728](https://user-images.githubusercontent.com/78781245/177956556-19e0ba59-7e62-437b-a5b7-8f05663e0b73.png)

**Comment by Anupriyabanger** [comment]
Notifications should also be deleted from notifications.
