### ISSUE TITLE
Create Byte> once updated privacy status does not change 

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#435]

**Comment by manojnegi07** [comment]
![image](https://user-images.githubusercontent.com/92147060/204469525-ebf5fc2b-e4f1-4e09-84dc-712a03af6aaf.png)
![image](https://user-images.githubusercontent.com/92147060/204469656-fad8fb15-2b38-495c-8bf1-3802c68d3439.png)
![image](https://user-images.githubusercontent.com/92147060/204469718-80deb3e8-4fcc-4410-9920-caf3062e763f.png)

**Comment by manojnegi07** [comment]
It is working fine
