### ISSUE TITLE
Social Events | Not able to edit my comment + reporting not working too

### ISSUE THREAD

**Issue by bidyut-majumdar** [manojnegi07/social-external#449]
![2022-12-18_085511](https://user-images.githubusercontent.com/78781245/208279956-a16a7aac-c23f-41ea-a7f7-41d5b1dd2714.png)

**Comment by Anupriyabanger** [comment]
@manojnegi07 was able to edit, but unable to report the comment. 
On reporting, the comment was still able to view the reported comment.
