### ISSUE TITLE
Event detail> No view option for Attendees Attendance 

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#465]
Where are we showing attendance data? 
![image](https://user-images.githubusercontent.com/109590553/208870981-85dbd8da-8ca4-46cd-b38e-7c467f4b65f2.png)

**Comment by manojnegi07** [comment]
for now only action button is there. where do you wanna show it @Anupriyabanger ?

**Comment by Anupriyabanger** [comment]
@manojnegi07 Not needed for now, as the attendance sheet has being updated in the resource section.
