### ISSUE TITLE
Profile> Activity section showing no data

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#475]
![image](https://user-images.githubusercontent.com/109590553/211308978-0cda84d8-0547-46de-8ad8-402f324022b1.png)

**Comment by manojnegi07** [comment]
![image](https://user-images.githubusercontent.com/92147060/215972458-4e6b6515-5ef9-49f5-bb30-a21d9e8b2a79.png)

**Comment by manojnegi07** [comment]
It is not related to profile. Will fix it in byte
