### ISSUE TITLE
#2023230110 Bookmark | Category created

### ISSUE THREAD

**Issue by manojnegi07** [manojnegi07/social-external#492]
“Category created !
This toast notification should come post creating a category not after creating a Bookmark. So fix the position for the same. Also for heaven sake stop using capital letters for every word use the format i have shared
![image](https://user-images.githubusercontent.com/92147060/213972824-8d9117fd-ad77-4dec-a283-7b60d44435e8.png)

**Comment by Anupriyabanger** [comment]
@manojnegi07, there is still a second. The category created and Bookmark created appears together.
