### ISSUE TITLE
#202331014 Byte | Create Byte - Issues while tagging people

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#524]
Tagging people is an issue, mostly you have to delete hyperlink to tag someone and then add hyperlink (refer image)
![image](https://user-images.githubusercontent.com/109590553/216539161-54144339-9955-4888-b175-42957e34b864.png)

**Comment by rgnarok** [comment]
<img width="764" alt="image" src="https://github.com/manojnegi07/social-external/assets/85341053/e0bf8242-2fec-4fc8-b344-2cb36f0778db">

Not working also hyperlink meta data is automatically getting disappeared while i am trying to tag people

**Comment by manojnegi07** [comment]
![image](https://github.com/manojnegi07/social-external/assets/92147060/46e4104c-24e9-4a18-ac15-154a225a6da7)

**Comment by Anupriyabanger** [comment]
The first name is not suggesting 
https://github.com/manojnegi07/social-external/assets/109590553/5e983fe0-bc1d-48a4-bd78-af04fa9b3d81
