### ISSUE TITLE
Byte | Create Byte - Hyperlink

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#525]
Hyperlink - Meta Description takes time to load

**Comment by Anupriyabanger** [comment]
@manojnegi07 Hyperlink is not visible.
![image](https://github.com/manojnegi07/social-external/assets/109590553/96ed247e-7b8e-47db-9d4d-b35bace7d75b)

**Comment by manojnegi07** [comment]
@Anupriyabanger  the current editor does not have any functionality to highlight perticular type of string .

**Comment by vayuzpriya** [comment]
![image](https://github.com/manojnegi07/social-external/assets/81085431/46ed4bda-113d-4b0b-a9a6-5ea5d7cc9904)
need to remove or set limit of description

**Comment by manojnegi07** [comment]
Added text limit of 75 characters
