### ISSUE TITLE
Byte | create byte> Hyperlink

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#526]
When you Remove Hyperlink, the Meta Description should automatically be removed too. Currently it stays there. 
![image](https://user-images.githubusercontent.com/109590553/216539603-21d161a5-c63e-4cc7-aad3-7e3fc6fc0ad8.png)

**Comment by Anupriyabanger** [comment]
Hyperlink is not visible. 
![image](https://github.com/manojnegi07/social-external/assets/109590553/eb823c5a-0172-4777-82f4-0de82e6ba832)

**Comment by rgnarok** [comment]
Metadata get removed for the first time but if I am trying to add the link again then the metadata not come up 
<img width="790" alt="image" src="https://github.com/manojnegi07/social-external/assets/85341053/709af31a-d584-4849-b646-cade3b92cde4">
