### ISSUE TITLE
#202302021 Bookmark | Create Bookmark

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#530]
It doesn't load meta description of load, please note that sometimes Bookmark can be simple url too.

**Comment by Anupriyabanger** [comment]
@manojnegi07 no meta description is loading.
![image](https://user-images.githubusercontent.com/109590553/216613871-d9c2e88a-0d9d-4206-934a-1cd2d3d7a9d8.png)

**Comment by manojnegi07** [comment]
Changed in Microservice
