### ISSUE TITLE
Create event> Editor> Emoji icon not visible

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#553]
![image](https://user-images.githubusercontent.com/109590553/216935285-cbeb999e-20af-402b-82b8-91049879a232.png)

**Comment by Anupriyabanger** [comment]
@bidyut-majumdar Still not visible enough 
****

**Comment by bidyut-majumdar** [comment]
@Anupriyabanger all the icon colors (3 dots dropdown to normal icons) are having same color for light / dark mode , same here , little changed, yet might look same.
