### ISSUE TITLE
Create event> Add media> No space between the media and attach media

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#554]
![image](https://user-images.githubusercontent.com/109590553/216935599-0a55d766-d775-4399-99d1-9e0f659b48f5.png)

**Comment by Anupriyabanger** [comment]
@bidyut-majumdar Too much space added
![image](https://user-images.githubusercontent.com/109590553/219328550-e5cd583a-f745-41b0-9b82-91b6233ce692.png)

**Comment by bidyut-majumdar** [comment]
@manojnegi07  after uploading files it is duplicating columns with blank data, please check

![2023-03-01_052749](https://user-images.githubusercontent.com/78781245/222010380-7a03b944-cdb7-4ad2-80e5-2f92082b4e08.png)
