### ISSUE TITLE
3 dots are not allinged properly - Safari

### ISSUE THREAD

**Issue by Mehulna** [manojnegi07/social-external#56]
![MicrosoftTeams-image (81)](https://user-images.githubusercontent.com/93506258/177967465-2eb77507-fed4-4e6b-b55d-f0e6d2deec27.png)

**Comment by rgnarok** [comment]
<img width="67" alt="image" src="https://user-images.githubusercontent.com/85341053/203312826-56590db4-b1ee-4e65-a154-14da1e722284.png">

working fine @Anupriyabanger  closing
