### ISSUE TITLE
Byte >event > dark mode> selected option turns all white on selecting

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#574]
![image](https://user-images.githubusercontent.com/109590553/217515318-9730a05f-cf15-480f-8536-a6d20f2efb22.png)

**Comment by vayuzpriya** [comment]
![image](https://github.com/manojnegi07/social-external/assets/81085431/6a10bdcc-4802-4d94-b015-8817736d3c32)
@Anupriyabanger  not visible this issue
