### ISSUE TITLE
Listing > Advanced Filters > On Applying Advance Filters the above filters - Upcoming New gets automatically removed 

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#633]
![image](https://user-images.githubusercontent.com/109590553/220276417-e2f612fd-2bd3-4739-9e08-a32cf911c8be.png)

**Comment by manojnegi07** [comment]
Yes it is don intentionally . Because we are applying filter on all data not a specific section that is why on applying filter we are hiding other sections
