### ISSUE TITLE
Detail> Header not fixed  

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#642]
![image](https://user-images.githubusercontent.com/109590553/220279248-0f77667f-165b-461d-829a-ffb46e184e1c.png)

**Comment by bidyut-majumdar** [comment]
@manojnegi07 please do the needful here

**Comment by manojnegi07** [comment]
@bidyut-majumdar  what need full i have to do here?

**Comment by bidyut-majumdar** [comment]
> @bidyut-majumdar what need full i have to do here?

Told you over call (Insight's dual header approach).
