### ISSUE TITLE
Create byte> Add check box to set as default for privacy

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#655]
![image](https://user-images.githubusercontent.com/109590553/220855583-f71b216f-0038-4c26-91c4-083b4e6b28b5.png)
![image](https://user-images.githubusercontent.com/109590553/220855621-5db2b787-f810-41d6-bce3-3b0869787e95.png)

**Comment by Anupriyabanger** [comment]
@manojnegi07 No change
![image](https://github.com/manojnegi07/social-external/assets/109590553/2b2d1631-6daf-4481-9e7b-7e6e8ef527f0)

**Comment by manojnegi07** [comment]
![image](https://github.com/manojnegi07/social-external/assets/92147060/ba319837-fbac-4be2-b561-0a3b12a65106)
Added on onrender
