### ISSUE TITLE
Create byte> add option to add feelings

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#660]
![image](https://user-images.githubusercontent.com/109590553/220860299-48f7a913-8195-486e-9ff3-cfb00bb24712.png)
![image](https://user-images.githubusercontent.com/109590553/220860362-0201234e-cfcb-4ee6-bad4-3b8a8625376e.png)
![image](https://user-images.githubusercontent.com/109590553/220860420-a2b781a5-c303-4767-b930-a1cc7a5f2f89.png)

**Comment by vayuzpriya** [comment]
activities are not added
