### ISSUE TITLE
Byte > Search icon's position is not same throughout the modules

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#664]
Byte:
![image](https://user-images.githubusercontent.com/109590553/221520930-f9a963dd-1ded-4e3c-9dbc-8582f931620c.png)
Insights
![image](https://user-images.githubusercontent.com/109590553/221521165-c812576c-4e50-4aaa-a434-854911a228aa.png)

**Comment by vayuzpriya** [comment]
In non - Microservice modals old version header is going. Need to change all modules in Micro services.

**Comment by manojnegi07** [comment]
It will be removed once all module converted in microservice. so closing this issue
