### ISSUE TITLE
Byte listing> Not able to open insights

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#688]
![image](https://user-images.githubusercontent.com/109590553/223351739-e993e28d-d152-48fd-92d2-2f0deba018c5.png)

**Comment by rgnarok** [comment]
<img width="1417" alt="image" src="https://github.com/manojnegi07/social-external/assets/85341053/94469737-cc8b-46d7-ac0c-6ba6de50e6dc">

Showing this on the link: https://social.vayuz.com/byte

and nothing happens on click on the card image or title for the link: https://social-byte.onrender.com/
It is only working when i click on comment please fix
