### ISSUE TITLE
Byte detail> Reaction count increasing on changing the reaction

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#702]
![image](https://user-images.githubusercontent.com/109590553/223378304-12c636d6-f2f0-41bc-9300-0e40875c07df.png)

**Comment by rgnarok** [comment]
<img width="528" alt="image" src="https://github.com/manojnegi07/social-external/assets/85341053/ad31ce6b-fa04-4e6c-a4b1-50a100231dbb">

Not fixed as I am adding reaction and then removing it and it is showing increase in count but it must be constant for a user
