### ISSUE TITLE
Private Event > No option to cancel invite

### ISSUE THREAD

**Issue by manojnegi07** [manojnegi07/social-external#707]

**Comment by Anupriyabanger** [comment]
Still No option to cancel 
![image](https://user-images.githubusercontent.com/109590553/224686190-371ade3d-7adb-4f39-828a-4c89e496880b.png)

**Comment by manojnegi07** [comment]
![image](https://github.com/manojnegi07/social-external/assets/92147060/a96bd85f-2191-4468-ba96-d49346988cee)

Added option to cancel on event detail page on invite modal
