### ISSUE TITLE
Social > Profile Image > Surname showing twice while displaying username details.

### ISSUE THREAD

**Issue by psharma1907** [manojnegi07/social-external#718]
![vsclss3](https://user-images.githubusercontent.com/123075948/225012394-6401d6ac-6508-472d-b355-f625e993d35b.jpg)

**Comment by Anupriyabanger** [comment]
@manojnegi07 Issue not resolved for every user
![image](https://github.com/manojnegi07/social-external/assets/109590553/5fdfd949-7065-459f-a1c8-d857a0cef8e2)

**Comment by manojnegi07** [comment]
@Anupriyabanger  it is not the issue here. it is showing because wrong data has been update
