### ISSUE TITLE
Byte detail> Remove back icon and add "x" icon to move to previous screen

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#752]
Keeping consistency on the platform.

**Comment by vayuzpriya** [comment]
![image](https://github.com/manojnegi07/social-external/assets/81085431/f8ff7d17-fd27-4cb0-8101-879708a7a8a8)
![image](https://github.com/manojnegi07/social-external/assets/81085431/9f0737c2-9bc2-42b3-a331-8af3926f6479)
already cross icon added.
