### ISSUE TITLE
#2022090711 Byte Detail | Edit Reply (Dark Mode)

### ISSUE THREAD

**Issue by vayuzpriya** [manojnegi07/social-external#76]
Please refer image, there are 2 issues:

1. Text except mention is not visible.
2. Cancel is not visible.
3. You can save without editing.

**Comment by vayuzpriya** [comment]
Text except mention is not visible. - fixed

**Comment by vayuzpriya** [comment]
Cancel is not visible. - fixed

**Comment by vayuzpriya** [comment]
You can save without editing. - left 
@manojnegi07

**Comment by Anupriyabanger** [comment]
<img width="251" alt="image" src="https://user-images.githubusercontent.com/109590553/190123002-c04bf43e-da09-41df-80ab-e20995834c60.png">

esc not working.
