### ISSUE TITLE
Create Event> Description> editor> Add link icon not working

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#783]

**Comment by manojnegi07** [comment]
@Anupriyabanger  there is no link icon in commenting. Please check it again . share screenshot if possible

**Comment by Anupriyabanger** [comment]
@manojnegi07 issue updated.
![image](https://user-images.githubusercontent.com/109590553/232774216-2fa4ff56-296f-410d-aa57-852219e81002.png)

**Comment by manojnegi07** [comment]
@Anupriyabanger  it is working fine. it is work when you select a text to link
