### ISSUE TITLE
Event> Resource> Add button not working 

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#784]

**Comment by Anupriyabanger** [comment]
@manojnegi07 Not able to add file 
![image](https://github.com/manojnegi07/social-external/assets/109590553/218adae5-878e-43b4-8fe0-e9a8d5659fa6)

**Comment by manojnegi07** [comment]
![image](https://github.com/manojnegi07/social-external/assets/92147060/43a76e17-2f81-4b36-8e10-3350493ddf5d)

@Anupriyabanger  it is working fine
