### ISSUE TITLE
#202209075 Byte Detail | Previous Comment (old reported issue)

### ISSUE THREAD

**Issue by vayuzpriya** [manojnegi07/social-external#82]
Use case: please check this Poll, it shows 2 comments but actually it has zero comments. It is showing 2 comments cause the last Byte I was checking had 2 comments and it picked up the value from the cache. As a result, its even showing Previous Comment>
![Uploading MicrosoftTeams-image (56).png…]()

**Comment by Anupriyabanger** [comment]
resolved.
