### ISSUE TITLE
#202209074 Byte Details | Comment / Reply Icon

### ISSUE THREAD

**Issue by vayuzpriya** [manojnegi07/social-external#83]
Also Priya Katiyar & Manoj Negi the main idea on Social was:

1. Comment or Reply icon should become FULL COLORED if I have replied to it else it should show comment icon with Border (not full icon or colored)
2. Please also add CORRECT EMOJI on the Reply part.
3. Also confirm by when you will RESOLVE Emoji issue.

**Comment by vayuzpriya** [comment]
1. Comment or Reply icon should become FULL COLORED if I have replied to it else it should show comment icon with Border (not full icon or colored) - Color is changed now but can't change icon because now i am using font awesome Duotone icons. on entire platform.

**Comment by manojnegi07** [comment]
We can only fill comment icon if i have replied on it. but can't fill reply icon because it will increase the api response time

**Comment by vayuzpriya** [comment]
1. Please also add CORRECT EMOJI on the Reply part.
2. Also confirm by when you will RESOLVE Emoji issue.
@manojnegi07  we need to add emojis here.

**Comment by vayuzpriya** [comment]
@manojnegi07 Pls check

**Comment by manojnegi07** [comment]
There is no saperate section for reply now.
so closing this issue
