### ISSUE TITLE
Event> On moving from Groups to Events, Old event UI is visible 

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#845]
![image](https://github.com/manojnegi07/social-external/assets/109590553/e759bb2e-edfd-480a-8a52-a4ace0d14943)

**Comment by rajasrivastava101** [comment]
![image](https://github.com/manojnegi07/social-external/assets/129847373/24cbbf90-30ec-41cb-996e-c8a34753596d)
Still its an old UI

**Comment by manojnegi07** [comment]
It is fixed. @ankit needs to change the header on group. Already shared with him

**Comment by rajasrivastava101** [comment]
![image](https://github.com/manojnegi07/social-external/assets/129847373/dfcc1f95-33e8-4a6b-a08f-86c7c8eae96b)
On moving from groups to events page is completely blank.
