### ISSUE TITLE
#202209072 Byte | URL in Create Byte

### ISSUE THREAD

**Issue by vayuzpriya** [manojnegi07/social-external#85]
Priya Katiyar showing the complete url in the Byte makes the Byte look very ugly especially when Meta details are also showing, can you please figure out alternative way of showing url. How are others doing it? Can we shorten the url automatically Manoj Negi

**Comment by Anupriyabanger** [comment]
URL is still not looking good @manojnegi07 
<img width="385" alt="image" src="https://user-images.githubusercontent.com/109590553/188816847-bced0c4c-3a66-419f-b412-c68f799438e5.png">

Can we show URL like this?
<img width="278" alt="image" src="https://user-images.githubusercontent.com/109590553/188816970-ca84d9c2-2535-47e9-b897-639866c2ca77.png">

**Comment by vayuzpriya** [comment]
@manojnegi07 how it is UI issue?
