### ISSUE TITLE
Byte> Not able to open Image on clicking the picture

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#851]
On mobile: not able to swipe the image
![image](https://github.com/manojnegi07/social-external/assets/109590553/e83d80d8-7a8f-4fb2-b888-52d85d1a4789)

**Comment by manojnegi07** [comment]
@Anupriyabanger cant include swiping it is conflicting with current code. It will be done in Microservice if not get conflicted
