### ISSUE TITLE
Bytes listing > UI 

### ISSUE THREAD

**Issue by rajasrivastava101** [manojnegi07/social-external#853]
![image](https://github.com/manojnegi07/social-external/assets/129847373/559247eb-158a-437f-acaf-18b3dbf35855)
horizontal scroller is coming over the delete modal.

**Comment by vayuzpriya** [comment]
![image](https://github.com/manojnegi07/social-external/assets/81085431/8627e3e3-19e4-4a82-9d9a-8366dc076033)
