### ISSUE TITLE
Byte> upload document > Not able to upload the document/scroll down to click post

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#859]
![image](https://github.com/manojnegi07/social-external/assets/109590553/881f2fa3-7aef-4647-b306-02c43c095de0)

**Comment by vayuzpriya** [comment]
![image](https://github.com/manojnegi07/social-external/assets/81085431/ee85f7a2-ff2e-4550-baa1-2276af46bae9)
Fixed
