### ISSUE TITLE
in active user visible when I an taging anyone 

### ISSUE THREAD

**Issue by vayuzpriya** [manojnegi07/social-external#888]
![image](https://github.com/manojnegi07/social-external/assets/81085431/fb17aa53-48d3-4783-bfb9-b6877ff8654c)

**Comment by Anupriyabanger** [comment]
Can't test, not able to tag any user
![image](https://github.com/manojnegi07/social-external/assets/109590553/99dd1502-a56f-479c-b697-9e802000a113)

**Comment by vayuzpriya** [comment]
![image](https://github.com/manojnegi07/social-external/assets/81085431/262a2c27-86cb-428b-a0ce-50d13632b3fb)
Adan account is visible here
