### ISSUE TITLE
Use Good looking icons

### ISSUE THREAD

**Issue by manojnegi07** [manojnegi07/social-external#889]
![image](https://github.com/manojnegi07/social-external/assets/92147060/5ab829ee-f187-4109-a353-b237aa93fcb7)

Icons used are too old fashioned and not properly aligned

**Comment by vayuzpriya** [comment]
icons are changed. let me know if any issue here

**Comment by manojnegi07** [comment]
Done

**Comment by manojnegi07** [comment]
Done
