### ISSUE TITLE
You may like to read > UI is not user friendly and UX is missing here.

### ISSUE THREAD

**Issue by manojnegi07** [manojnegi07/social-external#896]
![image](https://github.com/manojnegi07/social-external/assets/92147060/d4bdfb93-c087-4004-8608-ccc59f43f911)

we can show banner image of the article. Only title is not looking good

**Comment by rgnarok** [comment]
<img width="370" alt="image" src="https://github.com/manojnegi07/social-external/assets/85341053/63919bcc-6d97-46c9-8189-15ed1a3fa4a6">

It is not good as it looks cluttered and is not giving a good experience to the user

**Comment by vayuzpriya** [comment]
@manojnegi07 Make sure only one line is visible here in title
