### ISSUE TITLE
Feed | Reactions | Reaction Window showing "Connect" button beside users who are already connected with me

### ISSUE THREAD

**Issue by bidyut-majumdar** [manojnegi07/social-external#90]
1. Both the users are already connected with me, but still showing the connect button.
2. Upon clicking connect toast message showing the invitation sent and 2 new connection for the week appears below the profile, which is wrong.

![2022-07-13_065318](https://user-images.githubusercontent.com/78781245/178628458-dd0832aa-6f1e-419f-920f-8bc2512cda0e.png)

![2022-07-13_065556](https://user-images.githubusercontent.com/78781245/178628650-02262f35-7932-44eb-8ddb-c77a5c1c2622.png)

**Comment by Anupriyabanger** [comment]
done.
