### ISSUE TITLE
Byte | Create Byte | Background changer section position is not correct, going outside of left edge, but big space at right

### ISSUE THREAD

**Issue by bidyut-majumdar** [manojnegi07/social-external#91]
![SL1](https://user-images.githubusercontent.com/78781245/178630275-283758bb-4cbc-456a-896a-e230f6b9515f.png)

**Comment by Anupriyabanger** [comment]
<img width="143" alt="image" src="https://user-images.githubusercontent.com/109590553/188810996-b09dc2a0-be81-47f3-97d1-fdd56dd17e1c.png">

still, it's appearing the same. @vayuzpriya

**Comment by vayuzpriya** [comment]
![image](https://github.com/manojnegi07/social-external/assets/81085431/0fbc4338-212a-4dcf-b611-dbff1d5deaac)
this is coming like this
