### ISSUE TITLE
Text color in white, would look good in popup

### ISSUE THREAD

**Issue by technicalbirdVayuz** [manojnegi07/social-external#912]
![image](https://github.com/manojnegi07/social-external/assets/18699624/864226da-4b11-4a21-9163-e00ddcdf1a42)

**Comment by rgnarok** [comment]
On copping the byte the toast is not coming up please fix

**Comment by vayuzpriya** [comment]
![image](https://github.com/manojnegi07/social-external/assets/81085431/477876b0-e4eb-4561-b94e-f6cefc35f568)
Fixed
