### ISSUE TITLE
Create byte> By default functionality not working 

### ISSUE THREAD

**Issue by Anupriyabanger** [manojnegi07/social-external#919]
https://github.com/manojnegi07/social-external/assets/109590553/6a696a0c-296d-4307-ad18-b19141871a54

**Comment by rgnarok** [comment]
<img width="677" alt="image" src="https://github.com/manojnegi07/social-external/assets/85341053/895c5439-d1f2-40dc-969c-bd1cfa708f16">

<img width="804" alt="image" src="https://github.com/manojnegi07/social-external/assets/85341053/7711c576-54cf-41ee-a36c-9041572d0df0">

Not working after updating

**Comment by manojnegi07** [comment]
Working fine

https://github.com/manojnegi07/social-external/assets/92147060/7590fd70-1eec-4983-a7e8-daf466f238c3
