### ISSUE TITLE
Edit icon is in line with privacy icon & date

### ISSUE THREAD

**Issue by technicalbirdVayuz** [manojnegi07/social-external#931]
![image](https://github.com/manojnegi07/social-external/assets/18699624/e19e864f-eade-438b-b488-54ecaefefc44)

**Comment by rgnarok** [comment]
This is not coming please check if i am editing the post

**Comment by vayuzpriya** [comment]
@manojnegi07 Pls check comment here.

**Comment by manojnegi07** [comment]
![image](https://github.com/manojnegi07/social-external/assets/92147060/84a137bd-abe8-4008-8924-f4e5ccc6d69d)
