### ISSUE TITLE
When going to detail page then reactions popup is coming for 1 second

### ISSUE THREAD

**Issue by technicalbirdVayuz** [manojnegi07/social-external#941]

**Comment by rgnarok** [comment]
<img width="1435" alt="image" src="https://github.com/manojnegi07/social-external/assets/85341053/76216f4e-c917-472f-a716-f1e1dcd40095">

Not coming up please fix

**Comment by vayuzpriya** [comment]
@technicalbirdVayuz @Anupriyabanger Pls check and close
