### ISSUE TITLE
Please make it a proper section instead of giving it on create byte, we need to track mood of a user like we have it in thip lets discuss this 

### ISSUE THREAD

**Issue by rgnarok** [manojnegi07/social-external#945]
<img width="852" alt="image" src="https://github.com/manojnegi07/social-external/assets/85341053/c6af1c4e-44a3-4111-b070-56a5e0d8e6ba">
<img width="1440" alt="image" src="https://github.com/manojnegi07/social-external/assets/85341053/358d2067-e82f-4b77-a12f-9efccf8655cb">

**Comment by vayuzpriya** [comment]
this is how user feel at some time. not mood tracker. Mood tracker will be add on social.
