### ISSUE TITLE
I am able to edit shared byte text which is posted by other user

### ISSUE THREAD

**Issue by vayuzpriya** [manojnegi07/social-external#971]
![image](https://github.com/manojnegi07/social-external/assets/81085431/0692fc12-8fff-4aca-adde-7acfd17c3f3c)

**Comment by Anupriyabanger** [comment]
Not resolved, on detail screen
![image](https://github.com/manojnegi07/social-external/assets/109590553/995704da-032a-419f-b683-019218996d65)
