### ISSUE TITLE
Create Byte > Add only 6 background here and rest add on more page

### ISSUE THREAD

**Issue by vayuzpriya** [manojnegi07/social-external#972]
![image](https://github.com/manojnegi07/social-external/assets/81085431/c1bd40af-7938-4166-846b-8b897cc4948c)

**Comment by Anupriyabanger** [comment]
Why blank boxes are visible?
![image](https://github.com/manojnegi07/social-external/assets/109590553/a1a25131-fef8-4a83-8293-cd19dec48a5e)
