### ISSUE TITLE
Byte > Mobile view is having both vertical and horizontal scrolling

### ISSUE THREAD

**Issue by bidyut-majumdar** [manojnegi07/social-external#981]
![horizontal and vertical scrolling](https://github.com/manojnegi07/social-external/assets/78781245/78d5c21a-3be9-4082-b301-84142ea1f129)

**Comment by Anupriyabanger** [comment]
Nit resolved 
https://github.com/manojnegi07/social-external/assets/109590553/fba004e2-9f9f-4371-8ad5-e662b0520b5d
