### ISSUE TITLE
Create Byte > I am uploading 5 images, then edited byte to delete 4 images and update, but all 5 images are staying

### ISSUE THREAD

**Issue by VayuzBidyut** [manojnegi07/social-external#982]
![Image deleted, but after updating imaes are staying](https://github.com/manojnegi07/social-external/assets/78781245/07452396-6396-449a-97f6-302b48bd1a15)

**Comment by Anupriyabanger** [comment]
@manojnegi07 Not able to check this issue, as i am not able to edit the posted images
