### ISSUE TITLE
Create Byte > While chancing background the text color are not being changed, while color being missed

### ISSUE THREAD

**Issue by bidyut-majumdar** [manojnegi07/social-external#984]
![white color missing](https://github.com/manojnegi07/social-external/assets/78781245/eb89c628-4ea1-4e08-bf88-a1c87fa90576)

**Comment by Anupriyabanger** [comment]
Issue not resolved 
![Screenshot_20230912-165023_Chrome.jpg](https://github.com/manojnegi07/social-external/assets/109590553/0f586119-8038-46f9-a90a-400bc2952134)
