### ISSUE TITLE
Byte | Poll detail's comment section | Multiple issues on mobile view

### ISSUE THREAD

**Issue by bidyut-majumdar** [manojnegi07/social-external#99]
Upon clicking the poll's comment details section found multiple issues as listed below:

**Using dark mode**

1. Texts are in black in dark mode.
2. Reaction and reply icons are going in dark color also (though reaction bit visible while reply icon color is lesser visible).
3. The more or less option is making confusion if someone is sharing links in comments. In the screenshot kartikeya sir had shared a link, link is in red color and "less" option is too in red color making it believing that the less is part of the link as well.
4. The cross button of the comment container is no way accessible as its behind the comment box (z-index lower ?) .
5. As mentioned in the above point upon clicking the non-accessible cross option the comment menu is opening instead, but here too again issues as upon clicking "Report comment"  the "Report Byte" modal is appearing behind it making it again inaccessible unless I close the "Report comment" bottom sheet.
6. The "Comments" text at top left corner (opposite of cross button) is not visible also in dark mode.

**Using light mode**

After chancing dark to light still the comment window and all the above pointers section appearing in dark, so couldn't check how they would look in light mode.

![SL10](https://user-images.githubusercontent.com/78781245/178639065-daa65822-b886-40d1-9fa7-637785bac79c.png)
u
![SL9](https://user-images.githubusercontent.com/78781245/178639068-7ba51eb6-01af-40e6-9a63-baf9557696a5.png)

![SL11](https://user-images.githubusercontent.com/78781245/178639060-921da05b-7248-4fed-be24-424f1988b42d.png)

**Comment by Anupriyabanger** [comment]
All pointers done.
