### ISSUE TITLE
Create Byte > Please change/improve the upload document UI

### ISSUE THREAD

**Issue by bidyut-majumdar** [manojnegi07/social-external#992]
![WhatsApp Image 2023-08-24 at 09 0544 23](https://github.com/manojnegi07/social-external/assets/78781245/3a759b4d-3072-47e3-ba9e-be09b6c91a44)

**Comment by Anupriyabanger** [comment]
Same UI
![Screenshot_20230912-152414_Chrome.jpg](https://github.com/manojnegi07/social-external/assets/109590553/d0fc8ee9-fa03-42f2-a210-adcc3c524ad0)

**Comment by vayuzpriya** [comment]
@Anupriyabanger  In this screen only issue is button color and text size . That was changed. Let me know if yiu want anything else.
