### ISSUE TITLE
Byte Listing > Create Shoutout > The note text box should be required, not optional, horizontal scrolling happening,  button's positioning for mobile is not correct

### ISSUE THREAD

**Issue by bidyut-majumdar** [manojnegi07/social-external#994]
![WhatsApp Image 2023-08-24 at 09 05 22](https://github.com/manojnegi07/social-external/assets/78781245/823b5181-3b21-4858-851d-3f31a28bba3a)

**Comment by vayuzpriya** [comment]
Make the lottie file dynamic. 
Send button should be visible but when not added details then button is disabled when details are filled button enable.
