### ISSUE TITLE
Byte > Already reacted reaction size (ex: love reaction) is appearing smaller compared to icons next to them

### ISSUE THREAD

**Issue by bidyut-majumdar** [manojnegi07/social-external#995]
![WhatsApp Image 2023-08-24 at 09 05 24](https://github.com/manojnegi07/social-external/assets/78781245/b2b57af4-abae-42a8-ac52-eca84d380b03)

**Comment by Anupriyabanger** [comment]
UI still not correct
![Screenshot_20230911-190241_Chrome](https://github.com/manojnegi07/social-external/assets/109590553/00d69eb7-ce5b-413d-a790-dbfa9113541f)
